config/routes.rb
FinalProject::Application.routes.draw do
  root :to => 'home#index'

  post '/request/:id' => 'providers#join_patient_request', :as => :request
  delete '/request/:id' => 'providers#destroy_patient_request', :as => :request

  get '/patient_session' => 'patient_session#new'
  post '/patient_session' => 'patient_session#create'
  get 'patient_dashboard' => 'dashboards#index_patient'
  match '/patient/join/:id' => 'patients#join', :as => :join
  get '/patient_doctorlist' => 'patients#show_doctors'
  delete '/patient_doctorlist/:id' => 'patients#delete_doctor', :as => :delete_doctor
  get '/add_patient_photo' => 'patients#add_photo'
  post '/add_patient_photo' => 'patients#create_photo'

  get '/provider_session' => 'provider_session#new'
  post '/provider_session' => 'provider_session#create'
  get '/provider_dashboard' => 'dashboards#index_provider'
  get '/patient_requests' => 'providers#patient_requests'  #AJAX - Create a relationship between doctor and patient
  get '/provider_patientlist' => 'providers#show_patients'
  delete '/provider_patientlist/:id' => 'providers#delete_patient', :as => :delete_patient

  get '/logout' => 'patient_session#destroy'
  get '/doctor_data' => 'dashboards#doctor_data' #AJAX

end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  def patient_requests
    @requests = Request.where(:receiver_id => @auth)
  end

  def join_patient_request
    request = Request.find(params[:id])
    m = Matches.create(:patient_id => request.sender_id, :doctor_id => request.receiver_id)
    # Send a message to the patient that they have been accepted
    request.delete
    @patient = m.patient_id
  end

  def destroy_patient_request
    request = Request.find(params[:id])
    request.delete
    @requests = Request.where(:receiver_id => @auth)
  end

  def show_patients
    @matches = Matches.find_all_by_doctor_id(@auth[:id])
  end

  def delete_patient
    match = Matches.find(params[:id])
    match.delete
    @matches = Matches.find_all_by_patient_id(@auth[:id])
  end
end

app/views/providers/_patients.html.erb
<% if matches.any? %> 
  <% @matches.each do |match| %>
    <div class = "doctor_search">
      <div><%= Patient.find_by_id(match.patient_id).first_name %> <%= Patient.find_by_id(match.patient_id).last_name %></div>
      <div><%= Patient.find_by_id(match.patient_id).phone %></div>
      <div><%= Patient.find_by_id(match.patient_id).email %></div>
      <div><%= link_to "Remove Patient", delete_patient_path(match.id), method: :delete, data: { confirm: 'Are you sure?' }, :remote => :true %></div>
      <div><%= link_to "Send a message", root_path %></div>
      <div>Send visit information</div>
    </div><!-- doctor_search -->
  <% end %>
  
  <% else %>

    <div><h1>No Patients</h1></div> 
<% end %>

app/views/providers/_requests.html.erb
<% if requests.any? %>
  <div>
    <div><h1> You have new patient requests</h1></div>
    <% requests.each do |req| %>
      <div class = "doctor_search">
        Prospective Patient: <%= Patient.find_by_id(req.sender_id).first_name %> <%=Patient.find_by_id(req.sender_id).last_name %><br>
        Username: <%= Patient.find_by_id(req.sender_id).username %> <br>
        Phone: <%= Patient.find_by_id(req.sender_id).phone %> <br>
        <%= link_to "Accept Patient", request_path(req), :method => :post, :remote => :true %>, 
        <%= link_to "Reject Request", req, method: :delete, data: { confirm: 'Are you sure?' }, :remote => :true %>, 
        <%= link_to 'Send a Message', root_path %>
      </div><!-- .doctor_search -->
    <% end %>
  </div>

  <% else %>
    <div><h1> You have no new patient requests</h1></div>
<% end %>

app/views/providers/delete_patient.js.erb
$('#patient_requests').empty();
// $('#patient_requests').append("<%=j render :partial => 'patients', :locals => {:matches => @matches} %>");

app/views/providers/destroy_patient_request.js.erb
$('#patient_requests').empty();
$('#patient_requests').append("<%=j render :partial => 'requests', :locals => {:requests => @requests} %>");

app/views/providers/join_patient_request.js.erb
$('#patient_requests').empty();
$('#patient_requests').append("<div>You are now <%= Patient.find(@patient).first_name %> <%= Patient.find(@patient).last_name %>'s primary care provider!</div>");

app/views/providers/patient_requests.js.erb
$('#patient_requests').empty();
$('#patient_requests').append("<%=j render :partial => 'requests', :locals => {:requests => @requests} %>");

app/views/providers/show_patients.js.erb
$('#patient_requests').empty();
$('#patient_requests').append("<%=j render :partial => 'patients', :locals => {:matches => @matches} %>");