config/routes.rb
FinalProject::Application.routes.draw do
  root :to => 'home#index'

  post '/request/:id' => 'providers#join_patient_request', :as => :request
  delete '/request/:id' => 'providers#destroy_patient_request', :as => :request

  get '/patient_session' => 'patient_session#new'
  post '/patient_session' => 'patient_session#create'
  get 'patient_dashboard' => 'dashboards#index_patient'
  match '/patient/join/:id' => 'patients#join', :as => :join
  get '/patient_doctorlist' => 'patients#show_doctors'
  delete '/patient_doctorlist/:id' => 'patients#delete_doctor', :as => :delete_doctor
  get '/add_patient_photo' => 'patients#add_photo'
  post '/add_patient_photo' => 'patients#create_photo'

  get '/provider_session' => 'provider_session#new'
  post '/provider_session' => 'provider_session#create'
  get '/provider_dashboard' => 'dashboards#index_provider'
  get '/patient_requests' => 'providers#patient_requests'  #AJAX - Create a relationship between doctor and patient
  get '/provider_patientlist' => 'providers#show_patients'
  delete '/provider_patientlist/:id' => 'providers#delete_patient', :as => :delete_patient

  get '/logout' => 'patient_session#destroy'
  get '/doctor_data' => 'dashboards#doctor_data' #AJAX

end

app/models/patient.rb
# == Schema Information
#
# Table name: patients
#
#  id              :integer          not null, primary key
#  username        :string(255)
#  last_name       :string(255)
#  first_name      :string(255)
#  email           :string(255)
#  phone           :string(255)
#  password        :string(255)
#  password_digest :string(255)
#  age             :integer
#  photo_id        :integer
#  patient         :boolean
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Patient < ActiveRecord::Base
  #attr_accessible :photo_id, :remote_photo_url
  # mount_uploader :photos, PhotosUploader

  has_secure_password
  
  has_and_belongs_to_many :doctors
  has_and_belongs_to_many :illnesses
  has_many :appointments
  has_many :photos
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  def login
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to dashboard_index_path(user)
    else
        render :new #this is the new.html.erb page
    end
  end

  def edit
    @patient = Patient.find(params[:patient_id])  
  end

  def join
    r = Request.create(:sender_id => @auth[:id], :receiver_id => params[:id], :accepted => nil)
    # render :partial => 'success'
  end

  def show_doctors
    @matches = Matches.find_all_by_patient_id(@auth[:id])
  end

  def delete_doctor
    match = Matches.find(params[:id])
    match.delete
    @matches = Matches.find_all_by_patient_id(@auth[:id])
  end

  def add_photo
    @photo = Photo.new
    # @auth.photos << @photo
    # redirect_to patient_dashboard_path
  end

  def create_photo
    # raise params.inspect
    id = @auth.id
    binding.pry
    @photo = Photo.new(params[:photo])
    @photo.user_id = id
    @photo.save
    # if @photo.save
      redirect_to patient_dashboard_path
    # else
    #   render :add_photo
    # end
  end

end

app/views/patients/_doctors.html.erb
<% @matches.each do |match| %>
  <div class = "doctor_search">
    <div><%= Doctor.find_by_id(match.doctor_id).first_name %> <%= Doctor.find_by_id(match.doctor_id).last_name %></div>
    <div><%= Doctor.find_by_id(match.doctor_id).phone %></div>
    <div><%= Doctor.find_by_id(match.doctor_id).email %></div>
    <div><%= link_to "Remove Doctor", delete_doctor_path(match.id), method: :delete, data: { confirm: 'Are you sure?' }, :remote => :true %></div>
  </div><!-- doctor_search -->
<% end %>

app/views/patients/_photo.html.erb
<%=  form_for '/add_patient_photo', :html => { :multipart => true } do |f| %>
  
  <div class="field">
    <%= f.file_field :image %>
  </div>
  <div class="field">
   <%= f.label :name %>
   <%= f.text_field :name %>
  </div>
   <%= f.text_field :remote_image_url, :placeholder => "Or enter a url" %>

   <div class="submit"><%= f.submit %></div>
<% end %>

app/views/patients/add_photo.html.erb
<%= render 'photo' %>

app/views/patients/delete_doctor.js.erb
$('#doctor_list').empty();
$('#doctor_list').append("<%=j render :partial => 'doctors', :locals => {:matches => @matches} %>");

app/views/patients/join.js.erb
$('#doctor_list').empty();
$('#doctor_list').append('<div><h1>Request successfully sent!</h1></div>');

app/views/patients/show_doctors.js.erb
$('#doctor_list').empty();
$('#doctor_list').append("<%=j render :partial => 'doctors', :locals => {:matches => @matches} %>");