config/routes.rb
FinalProject::Application.routes.draw do
  root :to => 'home#index'

  post '/request/:id' => 'providers#join_patient_request', :as => :request
  delete '/request/:id' => 'providers#destroy_patient_request', :as => :request

  get '/patient_session' => 'patient_session#new'
  post '/patient_session' => 'patient_session#create'
  get 'patient_dashboard' => 'dashboards#index_patient'
  match '/patient/join/:id' => 'patients#join', :as => :join
  get '/patient_doctorlist' => 'patients#show_doctors'
  delete '/patient_doctorlist/:id' => 'patients#delete_doctor', :as => :delete_doctor
  get '/add_patient_photo' => 'patients#add_photo'
  post '/add_patient_photo' => 'patients#create_photo'

  get '/provider_session' => 'provider_session#new'
  post '/provider_session' => 'provider_session#create'
  get '/provider_dashboard' => 'dashboards#index_provider'
  get '/patient_requests' => 'providers#patient_requests'  #AJAX - Create a relationship between doctor and patient
  get '/provider_patientlist' => 'providers#show_patients'
  delete '/provider_patientlist/:id' => 'providers#delete_patient', :as => :delete_patient

  get '/logout' => 'patient_session#destroy'
  get '/doctor_data' => 'dashboards#doctor_data' #AJAX

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def index_patient

  end

  def index_provider

  end

  def doctor_data
    @docs = Doctor.all
  end
  
end

app/views/dashboards/doctor_data.js.erb
$('#doctor_list').empty();

<% @docs.each do |doc| %>
  doc = $('<div>');
  doc.addClass('doctor_search');
  $('#doctor_list').append(doc)
  doc.append('<div> <%= doc.first_name %> <%= doc.last_name %> </div>');
  doc.append('<div> <%= doc.phone %> </div>');
  doc.append('<div> <%= doc.email %> </div>');
  doc.append('<div> <%= link_to "Send a Message", root_path %> </div>');
  doc.append('<div> <%= link_to "Set an Appointment", root_path %> </div>');
  doc.append('<div> <%= link_to  "Request provider care", join_path(doc.id), remote: true  %></div>'); 
<% end %>

app/views/dashboards/index_patient.html.erb
<h1> Patient Dashboard </h1>
<div>Username: <%= @auth.username %> </div>
<div>Name: <%= @auth.first_name %> <%= @auth.last_name %> </div>
<div>Email: <%= @auth.email %> </div>
<div>Phone: <%= @auth.phone %> </div>
<div>Age: <%= @auth.age %> </div>
<!-- Put the photo in here -->

<div><%#= image_tag %></div>
<div><%= link_to "Edit Your Personal Info", root_path %></div>
<div><%= link_to "Add a photo", add_patient_photo_path %></div>
<div><%= link_to "Your Medical Providers", patient_doctorlist_path, remote: true %></div>
<div><%= link_to "List of Medications", root_path %></div>
<div><%= link_to "Current Illnesses", root_path %></div>
<div><%= link_to "Visit Info", root_path %></div>
<div><%= link_to "Make an Appointment", root_path %></div>
<div><%= link_to  "Click here to find a provider", "/doctor_data", remote: true %></div>

<!-- FOR AJAX TO TARGET-->
<div id="doctor_list"></div>

app/views/dashboards/index_provider.html.erb
<h1>Welcome back, Dr. <%= @auth.last_name %></h1>

<div>Username: <%= @auth.username %> </div>
<div>Name: <%= @auth.first_name %> <%= @auth.last_name %> </div>
<div>Email: <%= @auth.email %> </div>
<div>Phone: <%= @auth.phone %> </div>
<!-- Put the photo in here -->

<div><%= link_to "Edit Your Personal Info", root_path %></div>
<div><%= link_to "Messages", root_path %></div>
<div><%= link_to "Patients", provider_patientlist_path, :remote => true %></div>
<div><%= link_to "New Patient Requests", "/patient_requests", :remote => true %></div>
<div><%= link_to "Available Appointment Times", root_path %></div>

<!-- This is where new patient requests will come through AJAX-->
<div id="patient_requests"></div>